export const USER_ACTION_TYPES = {
    CHECK_USER_SESSION: 'user/CHECK_USER_SESSION',

    // sign in action types
    GOOGLE_SIGN_IN_START: 'user/GOOGLE_SIGN_IN_START',
    EMAIL_SIGN_IN_START: 'user/EMAIL_SIGN_IN_START',
    SIGN_IN_SUCCESS: 'user/SIGN_IN_SUCCESS',
    SIGN_IN_FAILED: 'user/SIGN_IN_FAILED',

    // sing up action types
    SIGN_UP_START: 'user/SIGN_UP_START',
    SIGN_UP_SUCCESS: 'user/SIGN_UP_SUCCESS',
    SIGN_UP_FAILED: 'user/SIGN_UP_FAILED',

    // sing out action types
    SIGN_OUT_START: 'user/SIGN_OUT_START',
    SIGN_OUT_SUCCESS: 'user/SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILED: 'user/SIGN_OUT_FAILED',

    // update current user
    UPDATE_USER_PROFILE_START: 'user/UPDATE_USER_PROFILE_START',
    UPDATE_USER_PROFILE_SUCCESS: 'user/UPDATE_USER_PROFILE_SUCCESS',
    UPDATE_USER_PROFILE_FAILED: 'user/UPDATE_USER_PROFILE_FAILED',
};
